/*
 * This is the main screen from where the program runs.
 */
package MainPackage;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;


public class FrontScreen extends javax.swing.JFrame implements ActionListener,ChangeListener{
    int x =0;
    int min = 0;
    int max = 10;
    int y = x;
    Timer tm;
    /**
     * Creates new form FrontScreen
     */
    public FrontScreen() {
       
        initComponents();
        this.setTitle("MAD at Sudoku");
        
        Image icon = Toolkit.getDefaultToolkit().getImage("src/sudoku/icon image.jpg");
        this.setIconImage(icon);
         this.getContentPane().setBackground(Color.WHITE);
         setSize(700, 700);
        jProgressBar1.setMaximum(max);
        jProgressBar1.setMinimum(min);
        jProgressBar1.setStringPainted(true);
        jProgressBar1.addChangeListener(this);
         this.setLocation(550, 150);
        
        tm = new Timer(3000,new ActionListener()
            
        {       @Override
    public void actionPerformed(ActionEvent e) {
       
      
       while(x<=100){
           jProgressBar1.setValue(x);
            x +=1;
       }
       x = 100;
    }  
        });
         
         tm.start();
         y = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jProgressBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProgressBar1MouseEntered(evt);
            }
        });
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(152, 573, 380, 47);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudoku/ezgif.com-video-to-gif (1).gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 610, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProgressBar1MouseEntered
        // TODO add your handling code here:
        MenuScreen ms = new MenuScreen();
        ms.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jProgressBar1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void stateChanged(ChangeEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
